name: Single Test Workflow

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Test tag (without @)'
        default: 'Smoke'
        required: true
        type: string

jobs:
  test:
    if: ${{ github.event_name != 'pull_request' || !contains(github.event.pull_request.title, '[skip-check]') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nanasess/setup-chromedriver@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven
      - name: Manual test @${{ github.event.inputs.tag }}
        if: ${{ github.event_name == 'workflow_dispatch'}}
        run: mvn test -Denv=ci -Dcucumber.filter.tags=@${{ github.event.inputs.tag }}
        working-directory: saucedemo-automation
      - name: Smoke test @${{ github.event.pull_request.title }}
        if: ${{ github.event_name == 'pull_request'}}
        run: mvn test -Denv=ci -Dcucumber.filter.tags=@${{ github.event.pull_request.title }}
        working-directory: saucedemo-automation
      - name: Cucumber Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: saucedemo-automation/target/cucumber-reports.html




